/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *Ctrl_L;
    QPushButton *Shift_L;
    QPushButton *Caps;
    QPushButton *Tab;
    QPushButton *Wave;
    QPushButton *One;
    QPushButton *Two;
    QPushButton *Three;
    QPushButton *Four;
    QPushButton *Seven;
    QPushButton *Eight;
    QPushButton *Nine;
    QPushButton *Five;
    QPushButton *Six;
    QPushButton *Zero;
    QPushButton *Bar;
    QPushButton *Plus;
    QPushButton *Backspace;
    QPushButton *Win_L;
    QPushButton *Ait;
    QPushButton *Zz;
    QPushButton *Xx;
    QPushButton *Vv;
    QPushButton *Cc;
    QPushButton *Bb;
    QPushButton *Mm;
    QPushButton *Rest;
    QPushButton *Spot;
    QPushButton *Nn;
    QPushButton *Slash;
    QPushButton *Shift_R;
    QPushButton *Ctrl_R;
    QPushButton *Change;
    QPushButton *Menu;
    QPushButton *Win_R;
    QPushButton *Space;
    QPushButton *Aa;
    QPushButton *Ss;
    QPushButton *Dd;
    QPushButton *Ff;
    QPushButton *Gg;
    QPushButton *Hh;
    QPushButton *Jj;
    QPushButton *Kk;
    QPushButton *Ll;
    QPushButton *Semicolon;
    QPushButton *Quotes;
    QPushButton *Enter;
    QPushButton *Clear;
    QPushButton *Copy;
    QPushButton *Qq;
    QPushButton *Ww;
    QPushButton *Ee;
    QPushButton *Rr;
    QPushButton *Tt;
    QPushButton *Uu;
    QPushButton *Yy;
    QPushButton *Ii;
    QPushButton *Pp;
    QPushButton *Oo;
    QPushButton *Parenthesis_Start;
    QPushButton *Parenthesis_Finsh;
    QPushButton *ReverseSlash;
    QLabel *Screen;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(675, 384);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(48, 47, 47);"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        Ctrl_L = new QPushButton(centralwidget);
        Ctrl_L->setObjectName(QString::fromUtf8("Ctrl_L"));
        Ctrl_L->setGeometry(QRect(5, 310, 51, 45));
        Ctrl_L->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Shift_L = new QPushButton(centralwidget);
        Shift_L->setObjectName(QString::fromUtf8("Shift_L"));
        Shift_L->setGeometry(QRect(5, 265, 81, 45));
        Shift_L->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Caps = new QPushButton(centralwidget);
        Caps->setObjectName(QString::fromUtf8("Caps"));
        Caps->setGeometry(QRect(5, 220, 71, 45));
        Caps->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Tab = new QPushButton(centralwidget);
        Tab->setObjectName(QString::fromUtf8("Tab"));
        Tab->setGeometry(QRect(5, 175, 61, 45));
        Tab->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Wave = new QPushButton(centralwidget);
        Wave->setObjectName(QString::fromUtf8("Wave"));
        Wave->setGeometry(QRect(5, 130, 45, 45));
        Wave->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        One = new QPushButton(centralwidget);
        One->setObjectName(QString::fromUtf8("One"));
        One->setGeometry(QRect(50, 130, 45, 45));
        One->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Two = new QPushButton(centralwidget);
        Two->setObjectName(QString::fromUtf8("Two"));
        Two->setGeometry(QRect(95, 130, 45, 45));
        Two->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Three = new QPushButton(centralwidget);
        Three->setObjectName(QString::fromUtf8("Three"));
        Three->setGeometry(QRect(140, 130, 45, 45));
        Three->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Four = new QPushButton(centralwidget);
        Four->setObjectName(QString::fromUtf8("Four"));
        Four->setGeometry(QRect(185, 130, 45, 45));
        Four->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Seven = new QPushButton(centralwidget);
        Seven->setObjectName(QString::fromUtf8("Seven"));
        Seven->setGeometry(QRect(320, 130, 45, 45));
        Seven->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Eight = new QPushButton(centralwidget);
        Eight->setObjectName(QString::fromUtf8("Eight"));
        Eight->setGeometry(QRect(365, 130, 45, 45));
        Eight->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Nine = new QPushButton(centralwidget);
        Nine->setObjectName(QString::fromUtf8("Nine"));
        Nine->setGeometry(QRect(410, 130, 45, 45));
        Nine->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Five = new QPushButton(centralwidget);
        Five->setObjectName(QString::fromUtf8("Five"));
        Five->setGeometry(QRect(230, 130, 45, 45));
        Five->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Six = new QPushButton(centralwidget);
        Six->setObjectName(QString::fromUtf8("Six"));
        Six->setGeometry(QRect(275, 130, 45, 45));
        Six->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Zero = new QPushButton(centralwidget);
        Zero->setObjectName(QString::fromUtf8("Zero"));
        Zero->setGeometry(QRect(455, 130, 45, 45));
        Zero->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Bar = new QPushButton(centralwidget);
        Bar->setObjectName(QString::fromUtf8("Bar"));
        Bar->setGeometry(QRect(500, 130, 45, 45));
        Bar->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Plus = new QPushButton(centralwidget);
        Plus->setObjectName(QString::fromUtf8("Plus"));
        Plus->setGeometry(QRect(545, 130, 45, 45));
        Plus->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Backspace = new QPushButton(centralwidget);
        Backspace->setObjectName(QString::fromUtf8("Backspace"));
        Backspace->setGeometry(QRect(590, 130, 81, 45));
        Backspace->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Win_L = new QPushButton(centralwidget);
        Win_L->setObjectName(QString::fromUtf8("Win_L"));
        Win_L->setGeometry(QRect(56, 310, 45, 45));
        Win_L->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ait = new QPushButton(centralwidget);
        Ait->setObjectName(QString::fromUtf8("Ait"));
        Ait->setGeometry(QRect(101, 310, 51, 45));
        Ait->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Zz = new QPushButton(centralwidget);
        Zz->setObjectName(QString::fromUtf8("Zz"));
        Zz->setGeometry(QRect(86, 265, 45, 45));
        Zz->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Xx = new QPushButton(centralwidget);
        Xx->setObjectName(QString::fromUtf8("Xx"));
        Xx->setGeometry(QRect(131, 265, 45, 45));
        Xx->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Vv = new QPushButton(centralwidget);
        Vv->setObjectName(QString::fromUtf8("Vv"));
        Vv->setGeometry(QRect(221, 265, 45, 45));
        Vv->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Cc = new QPushButton(centralwidget);
        Cc->setObjectName(QString::fromUtf8("Cc"));
        Cc->setGeometry(QRect(176, 265, 45, 45));
        Cc->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Bb = new QPushButton(centralwidget);
        Bb->setObjectName(QString::fromUtf8("Bb"));
        Bb->setGeometry(QRect(266, 265, 45, 45));
        Bb->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Mm = new QPushButton(centralwidget);
        Mm->setObjectName(QString::fromUtf8("Mm"));
        Mm->setGeometry(QRect(356, 265, 45, 45));
        Mm->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Rest = new QPushButton(centralwidget);
        Rest->setObjectName(QString::fromUtf8("Rest"));
        Rest->setGeometry(QRect(401, 265, 45, 45));
        Rest->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Spot = new QPushButton(centralwidget);
        Spot->setObjectName(QString::fromUtf8("Spot"));
        Spot->setGeometry(QRect(446, 265, 45, 45));
        Spot->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Nn = new QPushButton(centralwidget);
        Nn->setObjectName(QString::fromUtf8("Nn"));
        Nn->setGeometry(QRect(311, 265, 45, 45));
        Nn->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Slash = new QPushButton(centralwidget);
        Slash->setObjectName(QString::fromUtf8("Slash"));
        Slash->setGeometry(QRect(491, 265, 45, 45));
        Slash->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Shift_R = new QPushButton(centralwidget);
        Shift_R->setObjectName(QString::fromUtf8("Shift_R"));
        Shift_R->setGeometry(QRect(536, 265, 136, 45));
        Shift_R->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ctrl_R = new QPushButton(centralwidget);
        Ctrl_R->setObjectName(QString::fromUtf8("Ctrl_R"));
        Ctrl_R->setGeometry(QRect(620, 310, 51, 45));
        Ctrl_R->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Change = new QPushButton(centralwidget);
        Change->setObjectName(QString::fromUtf8("Change"));
        Change->setGeometry(QRect(479, 310, 51, 45));
        Change->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Menu = new QPushButton(centralwidget);
        Menu->setObjectName(QString::fromUtf8("Menu"));
        Menu->setGeometry(QRect(575, 310, 45, 45));
        Menu->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Win_R = new QPushButton(centralwidget);
        Win_R->setObjectName(QString::fromUtf8("Win_R"));
        Win_R->setGeometry(QRect(530, 310, 45, 45));
        Win_R->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Space = new QPushButton(centralwidget);
        Space->setObjectName(QString::fromUtf8("Space"));
        Space->setGeometry(QRect(152, 310, 327, 45));
        Space->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Aa = new QPushButton(centralwidget);
        Aa->setObjectName(QString::fromUtf8("Aa"));
        Aa->setGeometry(QRect(76, 220, 45, 45));
        Aa->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ss = new QPushButton(centralwidget);
        Ss->setObjectName(QString::fromUtf8("Ss"));
        Ss->setGeometry(QRect(121, 220, 45, 45));
        Ss->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Dd = new QPushButton(centralwidget);
        Dd->setObjectName(QString::fromUtf8("Dd"));
        Dd->setGeometry(QRect(166, 220, 45, 45));
        Dd->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ff = new QPushButton(centralwidget);
        Ff->setObjectName(QString::fromUtf8("Ff"));
        Ff->setGeometry(QRect(211, 220, 45, 45));
        Ff->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Gg = new QPushButton(centralwidget);
        Gg->setObjectName(QString::fromUtf8("Gg"));
        Gg->setGeometry(QRect(256, 220, 45, 45));
        Gg->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Hh = new QPushButton(centralwidget);
        Hh->setObjectName(QString::fromUtf8("Hh"));
        Hh->setGeometry(QRect(301, 220, 45, 45));
        Hh->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Jj = new QPushButton(centralwidget);
        Jj->setObjectName(QString::fromUtf8("Jj"));
        Jj->setGeometry(QRect(346, 220, 45, 45));
        Jj->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Kk = new QPushButton(centralwidget);
        Kk->setObjectName(QString::fromUtf8("Kk"));
        Kk->setGeometry(QRect(391, 220, 45, 45));
        Kk->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ll = new QPushButton(centralwidget);
        Ll->setObjectName(QString::fromUtf8("Ll"));
        Ll->setGeometry(QRect(436, 220, 45, 45));
        Ll->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Semicolon = new QPushButton(centralwidget);
        Semicolon->setObjectName(QString::fromUtf8("Semicolon"));
        Semicolon->setGeometry(QRect(481, 220, 45, 45));
        Semicolon->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Quotes = new QPushButton(centralwidget);
        Quotes->setObjectName(QString::fromUtf8("Quotes"));
        Quotes->setGeometry(QRect(526, 220, 45, 45));
        Quotes->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Enter = new QPushButton(centralwidget);
        Enter->setObjectName(QString::fromUtf8("Enter"));
        Enter->setGeometry(QRect(571, 220, 101, 45));
        Enter->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Clear = new QPushButton(centralwidget);
        Clear->setObjectName(QString::fromUtf8("Clear"));
        Clear->setGeometry(QRect(620, 70, 45, 45));
        Clear->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Copy = new QPushButton(centralwidget);
        Copy->setObjectName(QString::fromUtf8("Copy"));
        Copy->setGeometry(QRect(620, 15, 45, 45));
        Copy->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Qq = new QPushButton(centralwidget);
        Qq->setObjectName(QString::fromUtf8("Qq"));
        Qq->setGeometry(QRect(66, 175, 45, 45));
        Qq->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ww = new QPushButton(centralwidget);
        Ww->setObjectName(QString::fromUtf8("Ww"));
        Ww->setGeometry(QRect(111, 175, 45, 45));
        Ww->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ee = new QPushButton(centralwidget);
        Ee->setObjectName(QString::fromUtf8("Ee"));
        Ee->setGeometry(QRect(156, 175, 45, 45));
        Ee->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Rr = new QPushButton(centralwidget);
        Rr->setObjectName(QString::fromUtf8("Rr"));
        Rr->setGeometry(QRect(201, 175, 45, 45));
        Rr->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Tt = new QPushButton(centralwidget);
        Tt->setObjectName(QString::fromUtf8("Tt"));
        Tt->setGeometry(QRect(246, 175, 45, 45));
        Tt->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Uu = new QPushButton(centralwidget);
        Uu->setObjectName(QString::fromUtf8("Uu"));
        Uu->setGeometry(QRect(336, 175, 45, 45));
        Uu->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Yy = new QPushButton(centralwidget);
        Yy->setObjectName(QString::fromUtf8("Yy"));
        Yy->setGeometry(QRect(291, 175, 45, 45));
        Yy->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Ii = new QPushButton(centralwidget);
        Ii->setObjectName(QString::fromUtf8("Ii"));
        Ii->setGeometry(QRect(381, 175, 45, 45));
        Ii->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Pp = new QPushButton(centralwidget);
        Pp->setObjectName(QString::fromUtf8("Pp"));
        Pp->setGeometry(QRect(471, 175, 45, 45));
        Pp->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Oo = new QPushButton(centralwidget);
        Oo->setObjectName(QString::fromUtf8("Oo"));
        Oo->setGeometry(QRect(426, 175, 45, 45));
        Oo->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Parenthesis_Start = new QPushButton(centralwidget);
        Parenthesis_Start->setObjectName(QString::fromUtf8("Parenthesis_Start"));
        Parenthesis_Start->setGeometry(QRect(516, 175, 45, 45));
        Parenthesis_Start->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Parenthesis_Finsh = new QPushButton(centralwidget);
        Parenthesis_Finsh->setObjectName(QString::fromUtf8("Parenthesis_Finsh"));
        Parenthesis_Finsh->setGeometry(QRect(561, 175, 45, 45));
        Parenthesis_Finsh->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        ReverseSlash = new QPushButton(centralwidget);
        ReverseSlash->setObjectName(QString::fromUtf8("ReverseSlash"));
        ReverseSlash->setGeometry(QRect(606, 175, 65, 45));
        ReverseSlash->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123)"));
        Screen = new QLabel(centralwidget);
        Screen->setObjectName(QString::fromUtf8("Screen"));
        Screen->setGeometry(QRect(10, 10, 601, 111));
        Screen->setStyleSheet(QString::fromUtf8("background-color: gray;"));
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        Ctrl_L->setText(QCoreApplication::translate("MainWindow", "Ctrl", nullptr));
        Shift_L->setText(QCoreApplication::translate("MainWindow", "Shift", nullptr));
        Caps->setText(QCoreApplication::translate("MainWindow", "Caps", nullptr));
        Tab->setText(QCoreApplication::translate("MainWindow", "Tab", nullptr));
        Wave->setText(QString());
        One->setText(QString());
        Two->setText(QString());
        Three->setText(QString());
        Four->setText(QString());
        Seven->setText(QString());
        Eight->setText(QString());
        Nine->setText(QString());
        Five->setText(QString());
        Six->setText(QString());
        Zero->setText(QString());
        Bar->setText(QString());
        Plus->setText(QString());
        Backspace->setText(QCoreApplication::translate("MainWindow", "Backspace", nullptr));
        Win_L->setText(QCoreApplication::translate("MainWindow", "Win", nullptr));
        Ait->setText(QCoreApplication::translate("MainWindow", "Alt", nullptr));
        Zz->setText(QString());
        Xx->setText(QString());
        Vv->setText(QString());
        Cc->setText(QString());
        Bb->setText(QString());
        Mm->setText(QString());
        Rest->setText(QString());
        Spot->setText(QString());
        Nn->setText(QString());
        Slash->setText(QString());
        Shift_R->setText(QCoreApplication::translate("MainWindow", "Shift", nullptr));
        Ctrl_R->setText(QCoreApplication::translate("MainWindow", "Ctrl", nullptr));
        Change->setText(QString());
        Menu->setText(QCoreApplication::translate("MainWindow", "Menu", nullptr));
        Win_R->setText(QCoreApplication::translate("MainWindow", "Win", nullptr));
        Space->setText(QCoreApplication::translate("MainWindow", "Space", nullptr));
        Aa->setText(QString());
        Ss->setText(QString());
        Dd->setText(QString());
        Ff->setText(QString());
        Gg->setText(QString());
        Hh->setText(QString());
        Jj->setText(QString());
        Kk->setText(QString());
        Ll->setText(QString());
        Semicolon->setText(QString());
        Quotes->setText(QString());
        Enter->setText(QCoreApplication::translate("MainWindow", "Enter", nullptr));
        Clear->setText(QCoreApplication::translate("MainWindow", "Clear", nullptr));
        Copy->setText(QCoreApplication::translate("MainWindow", "Copy", nullptr));
        Qq->setText(QString());
        Ww->setText(QString());
        Ee->setText(QString());
        Rr->setText(QString());
        Tt->setText(QString());
        Uu->setText(QString());
        Yy->setText(QString());
        Ii->setText(QString());
        Pp->setText(QString());
        Oo->setText(QString());
        Parenthesis_Start->setText(QString());
        Parenthesis_Finsh->setText(QString());
        ReverseSlash->setText(QString());
        Screen->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
